"""update voucher audit fields

Revision ID: 71abebcdfbaa
Revises: a8cf4504c7cb
Create Date: 2025-12-25 23:29:21.301766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71abebcdfbaa'
down_revision: Union[str, Sequence[str], None] = 'a8cf4504c7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
