"""add_slug_into_brand_category

Revision ID: ver3
Revises: ver2
Create Date: 2025-12-30 21:28:24.703621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ver3'
down_revision: Union[str, None] = 'ver2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.add_column('categories', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_column('brands', 'slug')
    # ### end Alembic commands ###
