"""refactor conversation 

Revision ID: ver4
Revises: ver3
Create Date: 2026-01-01 23:16:17.292730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ver4'
down_revision: Union[str, None] = 'ver3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_id', sa.String(length=36), nullable=False))
    op.add_column('conversations', sa.Column('admin_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conversations_admin_id'), 'conversations', ['admin_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.drop_constraint('conversations_ibfk_1', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_ibfk_2', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['admin_id'], ['id'])
    op.drop_column('conversations', 'user2_id')
    op.drop_column('conversations', 'user1_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user1_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('conversations', sa.Column('user2_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_ibfk_2', 'conversations', 'users', ['user2_id'], ['id'])
    op.create_foreign_key('conversations_ibfk_1', 'conversations', 'users', ['user1_id'], ['id'])
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_admin_id'), table_name='conversations')
    op.drop_column('conversations', 'admin_id')
    op.drop_column('conversations', 'customer_id')
    # ### end Alembic commands ###
